# coding: utf-8

"""
    Samsara API

    Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.  # noqa: E501

    The version of the OpenAPI document: 2019-11-19
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from samsara.configuration import Configuration


class V1VisionRunByCameraResponseBooleanLogic(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'operator': 'str',
        'steps': 'list[V1VisionRunByCameraResponseBooleanLogicSteps]'
    }

    attribute_map = {
        'operator': 'operator',
        'steps': 'steps'
    }

    def __init__(self, operator=None, steps=None, local_vars_configuration=None):  # noqa: E501
        """V1VisionRunByCameraResponseBooleanLogic - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._operator = None
        self._steps = None
        self.discriminator = None

        if operator is not None:
            self.operator = operator
        if steps is not None:
            self.steps = steps

    @property
    def operator(self):
        """Gets the operator of this V1VisionRunByCameraResponseBooleanLogic.  # noqa: E501


        :return: The operator of this V1VisionRunByCameraResponseBooleanLogic.  # noqa: E501
        :rtype: str
        """
        return self._operator

    @operator.setter
    def operator(self, operator):
        """Sets the operator of this V1VisionRunByCameraResponseBooleanLogic.


        :param operator: The operator of this V1VisionRunByCameraResponseBooleanLogic.  # noqa: E501
        :type: str
        """

        self._operator = operator

    @property
    def steps(self):
        """Gets the steps of this V1VisionRunByCameraResponseBooleanLogic.  # noqa: E501


        :return: The steps of this V1VisionRunByCameraResponseBooleanLogic.  # noqa: E501
        :rtype: list[V1VisionRunByCameraResponseBooleanLogicSteps]
        """
        return self._steps

    @steps.setter
    def steps(self, steps):
        """Sets the steps of this V1VisionRunByCameraResponseBooleanLogic.


        :param steps: The steps of this V1VisionRunByCameraResponseBooleanLogic.  # noqa: E501
        :type: list[V1VisionRunByCameraResponseBooleanLogicSteps]
        """

        self._steps = steps

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1VisionRunByCameraResponseBooleanLogic):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1VisionRunByCameraResponseBooleanLogic):
            return True

        return self.to_dict() != other.to_dict()
