# coding: utf-8

"""
    Samsara API

    Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.  # noqa: E501

    The version of the OpenAPI document: 2019-11-19
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import samsara
from samsara.models.v1_document_field_type import V1DocumentFieldType  # noqa: E501
from samsara.rest import ApiException


class TestV1DocumentFieldType(unittest.TestCase):
    """V1DocumentFieldType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1DocumentFieldType(self):
        """Test V1DocumentFieldType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = samsara.models.v1_document_field_type.V1DocumentFieldType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
