# coding: utf-8

"""
    Samsara API

    Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.  # noqa: E501

    The version of the OpenAPI document: 2019-11-19
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import samsara
from samsara.models.address_geofence_response_polygon import AddressGeofenceResponsePolygon  # noqa: E501
from samsara.rest import ApiException


class TestAddressGeofenceResponsePolygon(unittest.TestCase):
    """AddressGeofenceResponsePolygon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddressGeofenceResponsePolygon(self):
        """Test AddressGeofenceResponsePolygon"""
        # FIXME: construct object with mandatory attributes with example values
        # model = samsara.models.address_geofence_response_polygon.AddressGeofenceResponsePolygon()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
