# coding: utf-8

"""
    Samsara API

    Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.  # noqa: E501

    The version of the OpenAPI document: 2019-11-19
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import samsara
from samsara.models.v1_vehicle_maintenance import V1VehicleMaintenance  # noqa: E501
from samsara.rest import ApiException


class TestV1VehicleMaintenance(unittest.TestCase):
    """V1VehicleMaintenance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1VehicleMaintenance(self):
        """Test V1VehicleMaintenance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = samsara.models.v1_vehicle_maintenance.V1VehicleMaintenance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
