# coding: utf-8

"""
    Samsara API

    Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.  # noqa: E501

    The version of the OpenAPI document: 2019-11-19
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import samsara
from samsara.models.v1_dvir_base_trailer_defects import V1DvirBaseTrailerDefects  # noqa: E501
from samsara.rest import ApiException


class TestV1DvirBaseTrailerDefects(unittest.TestCase):
    """V1DvirBaseTrailerDefects unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1DvirBaseTrailerDefects(self):
        """Test V1DvirBaseTrailerDefects"""
        # FIXME: construct object with mandatory attributes with example values
        # model = samsara.models.v1_dvir_base_trailer_defects.V1DvirBaseTrailerDefects()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
