# coding: utf-8

"""
    Samsara API

    Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.  # noqa: E501

    The version of the OpenAPI document: 2019-12-12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import samsara
from samsara.models.get_user_roles_response import GetUserRolesResponse  # noqa: E501
from samsara.rest import ApiException


class TestGetUserRolesResponse(unittest.TestCase):
    """GetUserRolesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetUserRolesResponse(self):
        """Test GetUserRolesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = samsara.models.get_user_roles_response.GetUserRolesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
