# coding: utf-8

"""
    Samsara API

    This is the Samsara API.  # noqa: E501

    The version of the OpenAPI document: 2019-12-12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import samsara
from samsara.models.v1_document_field_create import V1DocumentFieldCreate  # noqa: E501
from samsara.rest import ApiException

class TestV1DocumentFieldCreate(unittest.TestCase):
    """V1DocumentFieldCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1DocumentFieldCreate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = samsara.models.v1_document_field_create.V1DocumentFieldCreate()  # noqa: E501
        if include_optional :
            return V1DocumentFieldCreate(
                date_time_value = samsara.models.v1_document_field_create_date_time_value.V1DocumentFieldCreate_dateTimeValue(
                    date_time_ms = 10855639004823, ), 
                multiple_choice_value = [
                    samsara.models.v1_document_field_create_multiple_choice_value.V1DocumentFieldCreate_multipleChoiceValue(
                        selected = True, 
                        value = '0', )
                    ], 
                number_value = 12.34, 
                string_value = 'This is a string.', 
                value_type = 'ValueType_Number'
            )
        else :
            return V1DocumentFieldCreate(
                value_type = 'ValueType_Number',
        )

    def testV1DocumentFieldCreate(self):
        """Test V1DocumentFieldCreate"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
