# coding: utf-8

"""
    Samsara API

    This is the Samsara API.  # noqa: E501

    The version of the OpenAPI document: 2019-12-12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import samsara
from samsara.models.v1_data_input_history_response import V1DataInputHistoryResponse  # noqa: E501
from samsara.rest import ApiException

class TestV1DataInputHistoryResponse(unittest.TestCase):
    """V1DataInputHistoryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1DataInputHistoryResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = samsara.models.v1_data_input_history_response.V1DataInputHistoryResponse()  # noqa: E501
        if include_optional :
            return V1DataInputHistoryResponse(
                id = 12345, 
                name = 'Pump Flow', 
                points = [
                    samsara.models.v1_data_input_history_response_points.V1DataInputHistoryResponse_points(
                        time_ms = 1453449599999, 
                        value = 12.332, )
                    ]
            )
        else :
            return V1DataInputHistoryResponse(
                name = 'Pump Flow',
        )

    def testV1DataInputHistoryResponse(self):
        """Test V1DataInputHistoryResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
