# coding: utf-8

"""
    Samsara API

    This is the Samsara API.  # noqa: E501

    The version of the OpenAPI document: 2019-12-12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import samsara
from samsara.models.v1_hos_logs_response import V1HosLogsResponse  # noqa: E501
from samsara.rest import ApiException

class TestV1HosLogsResponse(unittest.TestCase):
    """V1HosLogsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1HosLogsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = samsara.models.v1_hos_logs_response.V1HosLogsResponse()  # noqa: E501
        if include_optional :
            return V1HosLogsResponse(
                logs = [
                    samsara.models.v1_hos_logs_response_logs.V1HosLogsResponse_logs(
                        codriver_ids = [
                            445.0
                            ], 
                        driver_id = 444, 
                        group_id = 101, 
                        hos_status_type = 'OFF_DUTY', 
                        loc_city = 'Ahwatukee', 
                        loc_lat = 23.413702, 
                        loc_lng = -98.50289, 
                        loc_name = 'McLean Site A', 
                        loc_state = 'Arizona', 
                        log_start_ms = 1462881998034, 
                        remark = 'Lunch Break', 
                        vehicle_id = 112, )
                    ]
            )
        else :
            return V1HosLogsResponse(
        )

    def testV1HosLogsResponse(self):
        """Test V1HosLogsResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
