# coding: utf-8

"""
    Samsara API

    Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.  # noqa: E501

    The version of the OpenAPI document: 2019-12-12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import samsara
from samsara.models.inline_object5 import InlineObject5  # noqa: E501
from samsara.rest import ApiException


class TestInlineObject5(unittest.TestCase):
    """InlineObject5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject5(self):
        """Test InlineObject5"""
        # FIXME: construct object with mandatory attributes with example values
        # model = samsara.models.inline_object5.InlineObject5()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
