# coding: utf-8

"""
    Samsara API

    This is the Samsara API.  # noqa: E501

    The version of the OpenAPI document: 2019-12-12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import samsara
from samsara.models.v1_dvir_list_response import V1DvirListResponse  # noqa: E501
from samsara.rest import ApiException

class TestV1DvirListResponse(unittest.TestCase):
    """V1DvirListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1DvirListResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = samsara.models.v1_dvir_list_response.V1DvirListResponse()  # noqa: E501
        if include_optional :
            return V1DvirListResponse(
                dvirs = [
                    samsara.models.v1_dvir_base.V1DvirBase(
                        author_signature = samsara.models.v1_dvir_base_author_signature.V1DvirBase_authorSignature(
                            driver_id = 2581, 
                            email = 'j.smith@yahoo.com', 
                            mechanic_user_id = 14849, 
                            name = 'John Smith', 
                            signed_at = 12535500000, 
                            type = 'driver', 
                            username = 'jsmith', ), 
                        defects_corrected = True, 
                        defects_need_not_be_corrected = False, 
                        id = 19, 
                        inspection_type = 'pre trip', 
                        mechanic_notes = 'The vehicle is now safe.', 
                        mechanic_or_agent_signature = samsara.models.v1_dvir_base_mechanic_or_agent_signature.V1DvirBase_mechanicOrAgentSignature(
                            driver_id = 2581, 
                            email = 'j.smith@yahoo.com', 
                            mechanic_user_id = 14849, 
                            name = 'John Smith', 
                            signed_at = 12535500000, 
                            type = 'driver', 
                            username = 'jsmith', ), 
                        next_driver_signature = samsara.models.v1_dvir_base_next_driver_signature.V1DvirBase_nextDriverSignature(
                            driver_id = 2581, 
                            email = 'j.smith@yahoo.com', 
                            name = 'John Smith', 
                            signed_at = 12535500000, 
                            type = 'driver', 
                            username = 'jsmith', ), 
                        odometer_miles = 49912, 
                        started_at_ms = 1453449599999, 
                        time_ms = 1453449599999, 
                        trailer_defects = [
                            samsara.models.v1_dvir_defect_base.V1DvirDefectBase(
                                comment = 'Air Compressor not working', 
                                defect_type = 'AIR_COMPRESSOR', 
                                id = 18, 
                                resolved = True, 
                                resolved_at = 1453449599999, 
                                resolved_by_driver_id = 2581, 
                                resolved_by_mechanic_id = 14849, )
                            ], 
                        trailer_id = 19, 
                        trailer_name = 'Storer's Trailer 19', 
                        vehicle = samsara.models.v1_dvir_base_vehicle.V1DvirBase_vehicle(
                            id = 19, 
                            name = 'Storer's vehicle 19', ), 
                        vehicle_condition = 'SATISFACTORY', 
                        vehicle_defects = [
                            samsara.models.v1_dvir_defect_base.V1DvirDefectBase(
                                comment = 'Air Compressor not working', 
                                defect_type = 'AIR_COMPRESSOR', 
                                id = 18, 
                                resolved = True, 
                                resolved_at = 1453449599999, 
                                resolved_by_driver_id = 2581, 
                                resolved_by_mechanic_id = 14849, )
                            ], )
                    ]
            )
        else :
            return V1DvirListResponse(
        )

    def testV1DvirListResponse(self):
        """Test V1DvirListResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
