# coding: utf-8

"""
    Samsara API

    This is the Samsara API.  # noqa: E501

    The version of the OpenAPI document: 2019-12-12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import samsara
from samsara.models.v1_document_all_of import V1DocumentAllOf  # noqa: E501
from samsara.rest import ApiException

class TestV1DocumentAllOf(unittest.TestCase):
    """V1DocumentAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1DocumentAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = samsara.models.v1_document_all_of.V1DocumentAllOf()  # noqa: E501
        if include_optional :
            return V1DocumentAllOf(
                document_type = 'Fuel Receipt', 
                driver_created_at_ms = 1462881998034, 
                driver_id = 555, 
                fields = [
                    null
                    ], 
                id = '2018_42424242', 
                org_id = 555, 
                server_created_at_ms = 1462881998034, 
                server_updated_at_ms = 1462881998034, 
                vehicle_id = 222
            )
        else :
            return V1DocumentAllOf(
                document_type = 'Fuel Receipt',
                driver_created_at_ms = 1462881998034,
                driver_id = 555,
                fields = [
                    null
                    ],
                id = '2018_42424242',
                org_id = 555,
                server_created_at_ms = 1462881998034,
                server_updated_at_ms = 1462881998034,
                vehicle_id = 222,
        )

    def testV1DocumentAllOf(self):
        """Test V1DocumentAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
