# coding: utf-8

"""
    Samsara API

    Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.  # noqa: E501

    The version of the OpenAPI document: 2019-12-12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import samsara
from samsara.models.v1_asset_reefer_response_reefer_stats_engine_hours import V1AssetReeferResponseReeferStatsEngineHours  # noqa: E501
from samsara.rest import ApiException


class TestV1AssetReeferResponseReeferStatsEngineHours(unittest.TestCase):
    """V1AssetReeferResponseReeferStatsEngineHours unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1AssetReeferResponseReeferStatsEngineHours(self):
        """Test V1AssetReeferResponseReeferStatsEngineHours"""
        # FIXME: construct object with mandatory attributes with example values
        # model = samsara.models.v1_asset_reefer_response_reefer_stats_engine_hours.V1AssetReeferResponseReeferStatsEngineHours()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
