# coding: utf-8

"""
    Samsara API

    This is the Samsara API.  # noqa: E501

    The version of the OpenAPI document: 2019-12-12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import samsara
from samsara.models.v1_document_create import V1DocumentCreate  # noqa: E501
from samsara.rest import ApiException

class TestV1DocumentCreate(unittest.TestCase):
    """V1DocumentCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1DocumentCreate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = samsara.models.v1_document_create.V1DocumentCreate()  # noqa: E501
        if include_optional :
            return V1DocumentCreate(
                document_type_uuid = '4aff772c-a7bb-45e6-8e41-6a53e34feb83', 
                fields = [
                    null
                    ], 
                dispatch_job_id = 773, 
                notes = 'Fueled up before delivery.', 
                state = 'Required'
            )
        else :
            return V1DocumentCreate(
                document_type_uuid = '4aff772c-a7bb-45e6-8e41-6a53e34feb83',
                fields = [
                    null
                    ],
        )

    def testV1DocumentCreate(self):
        """Test V1DocumentCreate"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
