# coding: utf-8

"""
    Samsara API

    Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.  # noqa: E501

    The version of the OpenAPI document: 2019-12-12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import samsara
from samsara.models.v1get_all_assets_response import V1getAllAssetsResponse  # noqa: E501
from samsara.rest import ApiException


class TestV1getAllAssetsResponse(unittest.TestCase):
    """V1getAllAssetsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1getAllAssetsResponse(self):
        """Test V1getAllAssetsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = samsara.models.v1get_all_assets_response.V1getAllAssetsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
