# coding: utf-8

"""
    Samsara API

    Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.  # noqa: E501

    The version of the OpenAPI document: 2019-12-12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import samsara_test
from samsara_test.models.address_response_core_all_of import AddressResponseCoreAllOf  # noqa: E501
from samsara_test.rest import ApiException


class TestAddressResponseCoreAllOf(unittest.TestCase):
    """AddressResponseCoreAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddressResponseCoreAllOf(self):
        """Test AddressResponseCoreAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = samsara_test.models.address_response_core_all_of.AddressResponseCoreAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
